url: "https://yahya.cc" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yahya.cc" # the name of your site, e.g. ACME Corp.
permalink: /:i_day/:short_month/:short_year/:title/
host: 0.0.0.0
port: 8080